/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessControl } from "./AccessControl";
export type { AccessControlDefaultAdminRules } from "./AccessControlDefaultAdminRules";
export type { IAccessControl } from "./IAccessControl";
export type { IAccessControlDefaultAdminRules } from "./IAccessControlDefaultAdminRules";
